### ISSUE TITLE
kitchen-dokken proxy support

### ISSUE THREAD

**Issue by st-isidore-de-seville** [someara/kitchen-dokken#1]
Hey @someara, in just a cursory reading of the documentation, I did not see anything regarding proxy support.  If it does not, would you accept a pull request :smile:

**Comment by someara** [comment]
indeed I would!

**Comment by st-isidore-de-seville** [comment]
@someara you are awesome.  I just came across this kitchen driver and it solves so many issues i was having.  Great job on this!

**Comment by st-isidore-de-seville** [comment]
@someara, quick question.  Why do I need to specify `driver: image:` like below:

```
  - name: centos-7
    driver:
      image: centos:7
```

Without it, I get 
```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #create action: [undefined method `split' for nil:NilClass]
>>>>>> ----------------------
```

I have not had to specify this in my `kitchen.yml` files before and was just curious.

**Comment by someara** [comment]
Other kitchen drivers attempt to guess image names based on convention... this makes you be explicit. No real reason other than the magic hasn't been coded into it

**Comment by st-isidore-de-seville** [comment]
So after playing around with this and looking at the Gem code, I actually reasoned that the `intermediate_instructions` hook actually would do the trick like below:

```
driver:
  name: dokken
  intermediate_instructions:
  - ENV http_proxy <%= ENV['http_proxy'] %>
  - ENV HTTP_PROXY <%= ENV['http_proxy'] %>
  - ENV https_proxy <%= ENV['https_proxy'] %>
  - ENV HTTPS_PROXY <%= ENV['https_proxy'] %>
  - ENV no_proxy <%= ENV['no_proxy'] %>
  - ENV NO_PROXY <%= ENV['no_proxy'] %>
```

If you feel that this is an appropriate use of `intermediate_instructions`, you can go ahead and close the issue.  

I look forward to playing around with this more and putting it through its paces :smile:

Thanks
