### ISSUE TITLE
provisioner configuration question

### ISSUE THREAD

**Issue by pantocrator27** [someara/kitchen-dokken#103]
working behind a proxy/firewall, on my kitchen-vagrant setup, I have the following configuration based on custom root certificates I am provisioning inside the box:

```
provisioner:
  name: chef_zero
  client_rb:
    ssl_ca_path: /etc/ssl/certs
```

I looked in the dokken code and could not find a similar construct.  I would expect that something like:

```
provisioner:
  name: dokken
  client_rb:
    ssl_ca_path: /etc/ssl/certs
```

would do this but it appears that it does not.
