### ISSUE TITLE
Can`t add network interface to docker container

### ISSUE THREAD

**Issue by rajiv-g** [someara/kitchen-dokken#104]
I am trying to add the network interface to the docker container.
```
---
driver:
  name: dokken
  privileged: true
  chef_version: 12.19.36
 
transport:
  name: dokken

provisioner:
  name: dokken
  environments_path: 'test/environments'
  roles_path: 'test/roles'
  client_rb:
    environment: test
    node_name: test-base

platforms:
- name: ubuntu-16.04
  driver:
    image: ubuntu:16.04
    platform: ubuntu
    pid_one_command: /bin/systemd
    intermediate_instructions:
    - RUN /usr/bin/apt-get update
suites:
- name: memcached
    driver:
      network:
      - ["private_network", {ip: "192.168.1.10"}]
    run_list:
      - role[memcached]
      - recipe[mycb::memcached]
```
But it is not reflected in the docker container.

```
root@test:/# ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:ac:11:00:02  
          inet addr:172.17.0.2  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:acff:fe11:2/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:68 errors:0 dropped:0 overruns:0 frame:0
          TX packets:30 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:3488 (3.4 KB)  TX bytes:2016 (2.0 KB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```
