### ISSUE TITLE
Docker for mac (native/xhyve)

### ISSUE THREAD

**Issue by rmoriz** [someara/kitchen-dokken#11]
Hi,

I'm running into the following error when using the new "native" Docker for mac:

```
-----> Starting Kitchen (v1.5.0)
-----> Creating <default-chef12-debian>...
       Finished creating <default-chef12-debian> (0m1.91s).
-----> Converging <default-chef12-debian>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 4.3.0...
       Removing non-cookbook files before transfer
       Preparing data_bags
       Preparing secret
       Preparing validation.pem
       Preparing client.rb
       Transferring files to <default-chef12-debian>
ssh: connect to host 127.0.0.1 port 32769: Connection refused
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-47/rsync/io.c(453) [sender=2.6.9]
[2016-04-07T10:57:06+00:00] WARN: *****************************************
[2016-04-07T10:57:06+00:00] WARN: Did not find config file: /opt/kitchen/client.rb, using command line options.
[2016-04-07T10:57:06+00:00] WARN: *****************************************
[2016-04-07T10:57:06+00:00] WARN: No cookbooks directory found at or above current directory.  Assuming /.
[2016-04-07T10:57:06+00:00] FATAL: Cannot load configuration from /opt/kitchen/dna.json

```

.kitchen.yml

```yaml

---
driver:
  name: dokken
  chef_version: 12.5.1

transport:
  name: dokken

provisioner:
  name: dokken

platforms:
  - name: debian
    driver:
      vm_hostname: ci-deployer
      image: debian:jessie

verifier:
  root_path: '/opt/verifier'
  sudo: false

suites:
  - name: default-chef12
    run_list:
      - recipe[org-base]
      - recipe[org-deployer]
```

versions:

```

kitchen-dokken (0.0.29, 0.0.25)
kitchen-inspec (0.12.2)
kitchen-vagrant (0.19.0, 0.18.0)
test-kitchen (1.5.0, 1.4.2, 1.4.0)
```

docker output after the error:

````
docker ps
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                         NAMES
21a2f1544962        default-chef12-debian:latest   "sh -c 'trap exit 0 S"   9 minutes ago       Up 9 minutes                                      default-chef12-debian
ccfa1f30eb02        someara/kitchen-cache:latest   "/usr/sbin/sshd -D -p"   9 minutes ago       Up 9 minutes        192.168.64.10:32769->22/tcp   default-chef12-debian-data

```
