### ISSUE TITLE
pid_one_command doesn't seem to be honored

### ISSUE THREAD

**Issue by tas50** [someara/kitchen-dokken#116]
I'm attempting to troubleshoot the joys of Debian 9 and the lack of systemd in the box. I was trying to set a different pid 1 command just so I could login to troubleshoot, but it doesn't seem possible:

```yaml
- name: debian-9
  driver:
    image: debian:9
    pid_one_command: /usr/sbin/service
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install apt-transport-https lsb-release procps net-tools -y
```

```
-----> Creating <resource-test-debian-9>...
       Creating kitchen sandbox at /Users/tsmith/.dokken/kitchen_sandbox/f8d8f7484c-resource-test-debian-9
       Creating verifier sandbox at /Users/tsmith/.dokken/verifier_sandbox/f8d8f7484c-resource-test-debian-9
       Building work image..
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [oci runtime error: container_linux.go:262: starting container process caused "exec: \"/bin/systemd\": stat /bin/systemd: no such file or directory"

] on resource-test-debian-9
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```
