### ISSUE TITLE
kitchen destroy doesn't cleanup kitchen_sandbox

### ISSUE THREAD

**Issue by jsirex** [someara/kitchen-dokken#120]
I'm not sure is it fixable. Chef creates some files like clients and nodes under the root user.
So when I issue kitchen destroy it writes "deleting sandbox.." but actually it does delete nothing.

Example:
```
rm: cannot remove '/home/sirex/.dokken/kitchen_sandbox/19d3009563-32x-centos-7/nodes': Permission denied
```

**Comment by majormoses** [comment]
I have seen this with a couple of our cookbooks that need to define nodes as well. I ended up throwing this into our Makefile and run this whenever we do use this in CI as a work around:
```
cleandokken: ## clean up dokken sensu dirs in ~/.dokken/kitchen_sandbox
	sudo chown -R ${USER}:${USER} ~/.dokken
	find ~/.dokken/kitchen_sandbox/ -maxdepth 1 -name '*-sensu-*' -type d -prune | xargs rm -rf
```

**Comment by someara** [comment]
I can't seem to reproduce this... 

Using the docker cookbook as a guinea pig... 

First, I remove ~/.dokken just to be sure there's nothing there, then I converging a random suite:

```bash
kitchen converge smoke-amazonlinux
```

Then, I checked it with `ls -laR ~/.dokken`

https://gist.github.com/someara/5b2eb2b75cf2e734f15808c4cddcc722

Everything seems to be owned by my local user.
This is with kitchen-dokken 2.5.1 on OSX.

**Comment by someara** [comment]
Are you using anything extra like maybe mwrock/kitchen-nodes?

**Comment by majormoses** [comment]
@someara yes we are using nodes so we can test that chef searches work for clients to find servers and such. I do not see that in our gemfiles so I think it's just using built in chef zero node support.

**Comment by jsirex** [comment]
I have the same configuration like docker cookbook.

```yaml
---
driver:
  name: dokken
  chef_version: 13.2.20
  privileged: true

provisioner:
  name: dokken

transport:
  name: dokken

verifier:
  name: inspec
  format: doc

platforms:
  - name: debian-8
    driver:
      image: dokken/debian-8
      pid_one_command: /bin/systemd
    run_list:
      - recipe[apt]
...
```
After destroying I see:
```bash
╰─○ pwd && ls -lha
/home/sirex/.dokken/kitchen_sandbox/19d3009563-32x-debian-9
total 28K
drwxr-xr-x  6 sirex sirex 4.0K Aug  5 15:35 .
drwxr-xr-x  3 sirex sirex 4.0K Aug  5 15:35 ..
drwxr-xr-x  3 sirex sirex 4.0K Aug  5 15:35 cache
drwx------  2 root  root  4.0K Aug  5 15:35 clients
drwxr-xr-x 12 sirex sirex 4.0K Aug  5 15:35 cookbooks
-rw-r--r--  1 sirex sirex   93 Aug  5 15:35 dna.json
drwx------  2 root  root  4.0K Aug  5 15:35 nodes
```
`clients` and `nodes` are created on runtime by chef during converge. So they have root ownership.
