### ISSUE TITLE
Debian 7 fails in privileged mode

### ISSUE THREAD

**Issue by djessich** [someara/kitchen-dokken#125]
The last 6 days I'm working on fixing the following problem that appears on a working Jenkins with working Docker installation on a CentOS 7 node. Jenkins itself was setup using a wrapper cookbook for the *jenkins* cookbook. The wrapper cookbook itself is executing the *docker* cookbook to install docker correctly (also installing the docker package using package resource produces the same problem).

During the converge of my test cookbook from a Jenkins Pipeline Job, all platforms are working properly, except Debian 7 (the Docker container is the official Debian 7 docker container; the one on the Docker Hub).  The problem on Debian 7 is, that converge fails during the "Installing Cookbook Gems" phase. Thereby kitchen shows the following error:

```
Installing Cookbook Gems:[0m
[0m
Running handlers:[0m
[2017-08-13T20:57:07+00:00] ERROR: Running exception handlers
Running handlers complete
[0m[2017-08-13T20:57:07+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 05 seconds[0m
[2017-08-13T20:57:07+00:00] FATAL: Stacktrace dumped to /opt/kitchen/cache/chef-stacktrace.out
[2017-08-13T20:57:07+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-08-13T20:57:07+00:00] ERROR: No such file or directory @ unlink_internal - /tmp/chef-gem-bundle20170813-222-1idergh
[2017-08-13T20:57:07+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
-----> Destroying <default-debian-7>...
       Deleting kitchen sandbox at /var/lib/jenkins/.dokken/kitchen_sandbox/89fcecfdb1-default-debian-7
       Deleting verifier sandbox at /var/lib/jenkins/.dokken/verifier_sandbox/89fcecfdb1-default-debian-7
       Finished destroying <default-debian-7> (0m10.83s).
rake aborted!
Kitchen::InstanceFailure: Converge failed on instance <default-debian-7>.  Please see .kitchen/logs/default-debian-7.log for more details
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/kitchen-dokken-2.6.1/lib/kitchen/provisioner/dokken.rb:59:in `rescue in call'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/kitchen-dokken-2.6.1/lib/kitchen/provisioner/dokken.rb:62:in `call'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:384:in `block in converge_action'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:489:in `block in action'
/opt/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:488:in `action'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:380:in `converge_action'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:359:in `block in transition_to'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:358:in `each'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:358:in `transition_to'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:157:in `verify'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:186:in `block in test'
/opt/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:182:in `test'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/rake_tasks.rb:59:in `block (3 levels) in define'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/opt/chefdk/embedded/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:216:in `block in invoke_prerequisites'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:214:in `each'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:214:in `invoke_prerequisites'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:193:in `block in invoke_with_call_chain'
/opt/chefdk/embedded/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/opt/chefdk/embedded/bin/rake:22:in `load'
/opt/chefdk/embedded/bin/rake:22:in `<main>'
Kitchen::ActionFailed: Docker Exec (1) for command: [/opt/chef/embedded/bin/chef-client -z -l warn -F doc -c /opt/kitchen/client.rb -j /opt/kitchen/dna.json]
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/kitchen-dokken-2.6.1/lib/kitchen/provisioner/dokken.rb:59:in `rescue in call'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/kitchen-dokken-2.6.1/lib/kitchen/provisioner/dokken.rb:62:in `call'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:384:in `block in converge_action'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:489:in `block in action'
/opt/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:488:in `action'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:380:in `converge_action'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:359:in `block in transition_to'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:358:in `each'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:358:in `transition_to'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:157:in `verify'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:186:in `block in test'
/opt/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:182:in `test'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/rake_tasks.rb:59:in `block (3 levels) in define'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/opt/chefdk/embedded/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:216:in `block in invoke_prerequisites'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:214:in `each'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:214:in `invoke_prerequisites'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:193:in `block in invoke_with_call_chain'
/opt/chefdk/embedded/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/opt/chefdk/embedded/bin/rake:22:in `load'
/opt/chefdk/embedded/bin/rake:22:in `<main>'
Kitchen::Transport::DockerExecFailed: Docker Exec (1) for command: [/opt/chef/embedded/bin/chef-client -z -l warn -F doc -c /opt/kitchen/client.rb -j /opt/kitchen/dna.json]
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/kitchen-dokken-2.6.1/lib/kitchen/transport/dokken.rb:76:in `execute'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/transport/base.rb:120:in `execute_with_retry'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/kitchen-dokken-2.6.1/lib/kitchen/provisioner/dokken.rb:51:in `block in call'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/transport/base.rb:90:in `initialize'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/kitchen-dokken-2.6.1/lib/kitchen/transport/dokken.rb:245:in `new'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/kitchen-dokken-2.6.1/lib/kitchen/transport/dokken.rb:245:in `create_new_connection'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/kitchen-dokken-2.6.1/lib/kitchen/transport/dokken.rb:57:in `connection'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/kitchen-dokken-2.6.1/lib/kitchen/provisioner/dokken.rb:44:in `call'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:384:in `block in converge_action'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:489:in `block in action'
/opt/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:488:in `action'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:380:in `converge_action'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:359:in `block in transition_to'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:358:in `each'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:358:in `transition_to'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:157:in `verify'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:186:in `block in test'
/opt/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:182:in `test'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/rake_tasks.rb:59:in `block (3 levels) in define'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/opt/chefdk/embedded/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:216:in `block in invoke_prerequisites'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:214:in `each'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:214:in `invoke_prerequisites'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:193:in `block in invoke_with_call_chain'
/opt/chefdk/embedded/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/opt/chefdk/embedded/bin/rake:22:in `load'
/opt/chefdk/embedded/bin/rake:22:in `<main>'
Tasks: TOP => integration:kitchen:all => integration:kitchen:default-debian-7
```

The configuration for Kitchen (.kitchen.dokken.yml):

```
---
driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_version: latest

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec
  format: doc

platforms:
  - name: centos-6
    driver:
      image: centos:6
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN yum -y install lsof which initscripts net-tools wget net-tools

  - name: centos-7
    driver:
      image: centos:7
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN yum -y install lsof which systemd-sysv initscripts wget net-tools

  - name: debian-7
    driver:
      image: debian:7
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get install apt-transport-https lsb-release procps net-tools -y

  - name: debian-8
    driver:
      image: debian:8
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get install apt-transport-https lsb-release procps net-tools -y

  - name: debian-9
    driver:
      image: debian:9
      pid_one_command: /usr/sbin/service
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get install apt-transport-https lsb-release procps net-tools -y

  - name: ubuntu-12.04
    driver:
      image: ubuntu:12.04
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get install apt-transport-https lsb-release procps net-tools -y

  - name: ubuntu-14.04
    driver:
      image: ubuntu:14.04
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get install apt-transport-https lsb-release procps net-tools -y

  - name: ubuntu-16.04
    driver:
      image: ubuntu:16.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get install apt-transport-https lsb-release procps net-tools -y

suites:
  - name: default
    run_list:
      - recipe[my-cookbook::default]
    attributes:
```

Very interesting is, that the problem appears only, if I start Kitchen on a privileged Debian 7 Docker container. Adding `privileged: false` to the config of Debian 7, seems to be working. However, as said before, all other configured platforms are working in privileged mode when converged during a Jenkins job.

Any ideas what circumstances may cause this problem appearing?
