### ISSUE TITLE
Load node data from nodes_path

### ISSUE THREAD

**Issue by Purple90** [someara/kitchen-dokken#132]
I switched over from vanilla test-kitchen to kitchen-dokken, and one thing that I cannot get to work, nor can I kind a solution online is the ability to load a node from the nodes_path: /foo/bar/node.json

My issue is I have a block in my cookbook that searched for a node with a specific recipe, and then takes a key from that node and sets it as a variable. 

My syntax is (sorry I have to hand type i:
```
provisioner:
  name: dokken
  client_rb:
    environment: stag
  resource_cloning: false
  nodes_path: test/integration/default/nodes
```
Insides the nodes folder, I have a simple json file called node.json
when I try to load data from it, nothing comes up (it doesn't even seem to load the node.json to the container)
