### ISSUE TITLE
data_image http/https proxy

### ISSUE THREAD

**Issue by bcg62** [someara/kitchen-dokken#147]
My CI jobs live behind a proxy and it seems like there is no way to interject intermediate steps or docker build-arg for the data_image.

https://github.com/someara/kitchen-dokken/blob/master/lib/kitchen/helpers.rb

This is an issue as I cannot install RPMs without the proxy properly being setup.

Am I missing something or someway to work around this? Maybe even being able to provide your own image here?

**Comment by joerg** [comment]
I also have to work in an airgapped environment without internet. We do have an Artifactory Server which has access to the internet and thus can proxy Docker and other repos.

```
---
driver:
  name: dokken
  chef_version: 12.12.13
  chef_image: docker.local.corp/chef/chef
  data_image: docker.local.corp/dokken/kitchen-cache:latest

driver_config:
  hostname: kitchen.local.corp

transport:
  name: dokken

provisioner:
  name: dokken
  client_rb:
    rubygems_url: https://local.corp/artifactory/api/gems/gems/

platforms:
  - name: rhel-6.9
    driver:
      image: docker.local.corp/redhat6-mini:6.9
  - name: rhel-7.4
    driver:
      image: docker.local.corp/redhat7-mini:7.4
      privileged: true
      pid_one_command: /usr/lib/systemd/systemd
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro # required by systemd

verifier:
  name: inspec

suites:
  - name: default
     ...
```

Where exactly does your kitchen run fail? Without logs it is hard to guess what the problem is.
