### ISSUE TITLE
Kitchen-Dokken Doesn't Appear to Support TEST_KITCHEN environment variable

### ISSUE THREAD

**Issue by AaronKalair** [someara/kitchen-dokken#176]
Hi,

The standard `test-kitchen` injects an environment variable called `TEST_KITCHEN` (see - https://github.com/test-kitchen/test-kitchen/pull/1081) 

However in `kitchen-dokken` this is not present, I did a little bit of digging and it appears that it's set in `test-kitchen` here - https://github.com/test-kitchen/test-kitchen/blob/9c771433645495500f0c6da21927208826ec8d5d/lib/kitchen/configurable.rb#L349 

And then anything that later on executes shell commands wraps there calls with that function - https://github.com/test-kitchen/test-kitchen/search?q=wrap_shell_code&unscoped_q=wrap_shell_code 

Should `kitchen-dokken` support the `TEST_KITCHEN` environment variable like `test-kitchen` / is there another way I can detect if I'm in a test envrionment?

Thank You

**Comment by ayanich** [comment]
if you use policy files for your test kitchen, you can do a `node.policy_group() == local` to see if you are in a test-kitchen since tk sets your policy_group to local

**Comment by smaslennikov** [comment]
This was an annoying surprise to me. I ended up setting an attribute in `.kitchen.yml`:

```yaml
...
suites:
  - name: testing
    run_list:
      - recipe[stuff::default]
    data_bags_path: '../../databags'
    attributes:
      kitchen_testing: true
```

...and checking for it in some recipes:
```
...
unless node[:kitchen_testing]
  service 'needs-cloud' do
    action [:enable, :start]
  end
end
```
