### ISSUE TITLE
Where should chef_license be set?

### ISSUE THREAD

**Issue by zedtux** [someara/kitchen-dokken#180]
When I'm running the `converge` command, I'm getting the following error :

```
-----> Starting Kitchen (v1.24.0)
-----> Converging <default-debian-9>...
       Creating kitchen sandbox in /Users/zedtux/.dokken/kitchen_sandbox/c7f22cb548-default-debian-9
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 7.0.7...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
Chef Infra Client cannot execute without accepting the license
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-debian-9>.  Please see .kitchen/logs/default-debian-9.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

There are couple of ways to accept the licence [as described on the Chef website](https://docs.chef.io/chef_license_accept.html), one of them is to set the `chef_license` attribute to 'accept'.

I found a Chef repo where this attribute is defined at the `provisioner` node :

```yaml
provisioner:
  name: dokken
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  chef_license: 'accept'
```

But it doesn't work for me.

Where should I do that with dokken please?
