### ISSUE TITLE
update README for enabling systemd services [centos]

### ISSUE THREAD

**Issue by chrisduong** [someara/kitchen-dokken#22]
Hi,

Regarding to Docker Hub for `centos image`, to enable **systemd** we need to run in **privileged mode** and mount **/sys/fs/cgroup**, otherwise **systemctl** would complain not having permission.

For e.g, my kitchen yml file for CentOS 7 would be.

```
platforms:
- name: centos-7
  driver:
    image: centos:7
    pid_one_command: /usr/sbin/init
    privileged: true
    intermediate_instructions:
      - ENV container docker
      - VOLUME [ "/sys/fs/cgroup" ]
```
