### ISSUE TITLE
hostname not working on centos-6

### ISSUE THREAD

**Issue by mengesb** [someara/kitchen-dokken#36]
I'm new to dokken; so forgive me.

I've got the following:

```

---
driver:
    name: dokken
    chef_version: latest
    privileged: true

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
  - name: centos-6.8
    driver:
      image: centos:6.8
      platform: rhel
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN yum -y install which initscripts
      forward:
        - 80
        - 443

  - name: ubuntu-precise
    driver:
      image: ubuntu-upstart:12.04
      platform: ubuntu
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN /usr/bin/apt-get -y update
        - RUN /usr/bin/apt-get -y install apt-transport-https
      forward:
        - 80
        - 443

  - name: ubuntu-trusty
    driver:
      image: ubuntu-upstart:14.04
      platform: ubuntu
      pid_one_command: /sbin/init
      provision_command:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get install apt-transport-https net-tools -y
      forward:
        - 80
        - 443

suites:
  - name: default
    driver:
      hostname: compliance.localdomain.local
    run_list:
      - recipe[chef-compliance]
    attributes:
      chef-compliance:
        api_fqdn: 'compliance.localdomain.local'
        accept_license: true
```

It would seem that `/proc/sys/kernel/hostname` isn't being set correctly on centos vs ubuntu containers:

```
[root@localhost /]# cat /etc/centos-release
CentOS release 6.8 (Final)
[root@localhost /]# cat /proc/sys/kernel/hostname
localhost.localdomain
```

```
root@compliance:/# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty
root@compliance:/# cat /proc/sys/kernel/hostname
compliance.localdomain.local
```
