### ISSUE TITLE
Not using the most recent version of Chef

### ISSUE THREAD

**Issue by kylegoch** [someara/kitchen-dokken#55]
With this kitchen.yml
```
---
driver:
  name: dokken
  chef_version: latest
  privileged: true
transport:
  name: dokken
provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
      image: ubuntu:16.04
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get install apt-transport-https net-tools -y

suites:
  - name: default
    run_list:
      - recipe[chef_role_jenkins::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
```

I am getting chef version 12.16.42 instead of 12.77.44. I thought it was becuase my ChefDK was one version behind, but I updated and still have the issue.

Is there something I may have missed somewhere that has me stuck on 12.16.42?
