### ISSUE TITLE
Possible to sync folders?

### ISSUE THREAD

**Issue by atheiman** [someara/kitchen-dokken#63]
I know little about docker, but is it possible to sync folders into the running container like you can with kitchen vagrant? I want to load a library from my cookbook during a test, currently I run this in my spec_helper.rb:

```ruby
load '/opt/kitchen/cookbooks/my_cookbook/libraries/my_library.rb'
```

Is there a better approach Im not thinking of?

**Comment by someara** [comment]
You can use "volumes" in the driver config to mount directories.
```yaml
driver:
  name: dokken
  chef_version: latest
  privileged: true # because Docker and SystemD/Upstart
  volumes: [ "stuff:/stuff", "more/stuff:/usr/src/morestuff" ]
```
