### ISSUE TITLE
chef_binary appears to be hardcoded to /opt/chef/embedded/bin/chef-client

### ISSUE THREAD

**Issue by jason-riddle** [someara/kitchen-dokken#83]
I have the following `.kitchen.dokken.yml` file.

```yml
driver:
  name: dokken
  chef_image: '<snipped>/chefdk'
  chef_version: xenial-20170123
  chef_binary: '/opt/chefdk/bin/chef-client'
```

Running kitchen converge fails with the following.

```bash
-----> Starting Kitchen (v1.16.0)
-----> Converging <default-amazonlinux-201609>...
       Creating kitchen sandbox in /Users/<snipped>/b441466084-default-amazonlinux-201609
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 5.6.3...
       Removing non-cookbook files before transfer
       Preparing data_bags
       Preparing secret
       Preparing validation.pem
       Preparing client.rb
rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "
exec: \"/opt/chef/embedded/bin/chef-client\": stat /opt/chef/embedded/bin/chef-client: no such file or directory"
```

My `kitchen-dokken` version.

```bash
chef exec gem list | grep dokken

kitchen-dokken (2.1.2)
```
