### ISSUE TITLE
kitchen-dokken Not Working with CircleCI

### ISSUE THREAD

**Issue by LevonBecker** [someara/kitchen-dokken#88]
I searched around and didn't see a solution. So, entering an issue...

## Problem
Using kitchen-dokken to do integration tests with CircleCI fail.

## Error
```
Kitchen::ActionFailed: Failed to complete #converge action: [Unsupported: Exec is not supported by the lxc driver
]
```
Here's an example failed build... https://circleci.com/gh/bonusbits/bonusbits_base/27

## Possible Issue
From what I've read CircleCI uses a legacy Docker execution driver **lxc** and the current **native** driver is not supported yet.

I'm assuming this gem uses the new cooler **native** driver.

Is there an attribute to force the gem to use the older driver or maybe it can be added?

Here is CircleCI's [workaround](https://circleci.com/docs/1.0/docker/#docker-exec)

## Notes
* I don't know enough about the difference or how it works to attempt a fix/PR or I would.
* Also, I'm guessing on some of my docker/dokken settings from examples I've found
* One thing I found is you HAVE to put quotes around the **chef_version** for it to work (Maybe be something to look into)

#### System
* macOS 10.12.4
* ChefDK 1.2.22
    * kitchen-dokken (1.1.0)
    * kitchen-inspec (0.17.0)
    * test-kitchen (1.15.0)

#### Example Kitchen Config
```yaml
---

driver:
  name: dokken
  chef_version: '12.18.31'
  privileged: true # because Docker and SystemD/Upstart
  volumes: '/var/lib/docker'
  driver_config:
    ssl_verify_mode: ":verify_none"

transport:
  name: dokken

verifier:
  name: inspec
  format: doc
#  format: junit
#  output: test/inspec/results/%{platform}_%{suite}_inspec.xml
#  output: $CIRCLE_TEST_REPORTS/inspec/results/%{platform}_%{suite}_inspec.xml

provisioner:
  name: dokken
  data_bags_path: test/data_bags
  encrypted_data_bag_secret_key_path: test/data_bags/encrypted_data_bag_secret
  roles_path: test/roles
  environments_path: test/environments
  chef_log_level: info

platforms:
  - name: amazon
    driver_config:
      image: amazonlinux:latest
      intermediate_instructions:
        - RUN yum -y install upstart procps util-linux
      pid_one_command: /sbin/init

suites:
  - name: base_docker
    run_list:
      - role[base]
    verifier:
      inspec_tests:
        - name: bootstrap
          git: https://github.com/bonusbits/inspec_bootstrap.git
        - name: bonusbits_base
          git: https://github.com/bonusbits/inspec_bonusbits_base.git
      attributes:
        chef_version: 12.18.31
        inside_aws: false
        configure_sudoers: true
    provisioner:
      client_rb:
        environment: "bonusbits_base"
    attributes:
      bonusbits_base:
        deployment_type: docker
        aws:
          inside: false
    includes: ["amazon"]
```

#### Example CircleCI Config
```yaml
machine:
  services:
    - docker
  ruby:
    version: '2.3.1'
  timezone:
    America/Los_Angeles

dependencies:
  override:
    - bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3:
      timeout: 900

test:
  override:
    - mkdir -p $CIRCLE_TEST_REPORTS/inspec/results
    - bundle exec rake circleci --trace:
      parallel: false
      timeout: 1800
```
