### ISSUE TITLE
Use name as image name?

### ISSUE THREAD

**Issue by chris-rock** [someara/kitchen-dokken#9]
Would it be possible to do something like:

```
platforms:
 - name: ubuntu:12.04
 - name: ubuntu:14.04
```

instead of

```
platforms:
- name: ubuntu-12.04
  driver:
      image: ubuntu:12.04
- name: ubuntu-14.04
  driver:
      image: ubuntu:14.04
```

Also I get the following error, if I do not add the driver image: `Message: Failed to complete #create action: [undefined method`split' for nil:NilClass]`
