### ISSUE TITLE
Use name as image name? (second one..)

### ISSUE THREAD

**Issue by StephenKing** [someara/kitchen-dokken#91]
Hi,

as #9 was closed due to age, I want to re-raise this.

As a novel and lazy user, I just want to copy over a minimal version of `.kitchen.dokken.yml` and use my platform definitions from my `.kitchen.yml` (as it used to work with _kitchen-docker_):

```yaml
driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart

transport:
  name: dokken

provisioner:
  name: dokken
```

The resulting error is said

> undefined method `split' for nil:NilClass

caused by [`parse_image_name`](https://github.com/someara/kitchen-dokken/blob/2ef7992064516a4983cc56f716adccc98ce1c9a3/lib/kitchen/driver/dokken.rb#L326) in the driver. This assumes a `repo:tag` value for the `image:` configuration option.

The same happens, when a lazy user tries to declare platforms as follows and "forgets" the `image:` declaration:

```yaml
platforms:
- name: debian-9
- name: debian-8
```
As the error message is pretty useless, **I see two options for improvement**:

- ensure that an `image` is defined for every platform, otherwise fail with directions to fix the error
- implement the logic as requested #9 and [as in _kitchen-docker_](https://github.com/test-kitchen/kitchen-docker/blob/08fbc005dad72a4d5ba86b3190b65f7aa9ce93d2/lib/kitchen/driver/docker.rb#L106-L112) (which worked for me very well for Ubuntu/Debian containers) and derive the image name from the name of the platform.

The second variant would also allow to leave out the `platforms:` part from `.kitchen.dokken.yml` and reuse the platforms defined in `.kitchen.yml` (which would be nice for our use case).

What option would be preferred?
